version: '3.8'
services:
  frontend:
    image: childaz/234-deploylab-frontend:update-html-content
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9999:80"
      - "8086:80"
    environment:
      - PORT=80
