name: Deploy frontend application
'on':
  push:
    branches:
      - main
      - update-html-content  # 添加新分支触发
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: childaz/234-deploylab-frontend:latest

      - name: Create remote directory
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/frontend
            chmod 755 /home/ubuntu/frontend

      - name: Upload compose files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          source: "docker-compose*.yml"  # 上传所有匹配的compose文件
          target: "/home/ubuntu/frontend/"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            echo "=== Current directory ==="
            pwd
            echo "=== Directory contents ==="
            ls -la /home/ubuntu/frontend
            echo "=== Branch: ${{ github.ref }} ==="

            cd /home/ubuntu/frontend

            # 根据分支选择部署配置
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "=== Deploying to port 8086 ==="
              docker compose -f docker-compose.yml down || true
              docker compose -f docker-compose.yml pull
              docker compose -f docker-compose.yml up -d
            elif [[ "${{ github.ref }}" == "refs/heads/update-html-content" ]]; then
              echo "=== Deploying to port 9999 ==="
              docker compose -f docker-compose-prod.yml down || true
              docker compose -f docker-compose-prod.yml pull
              docker compose -f docker-compose-prod.yml up -d
            else
              echo "Unknown branch, skipping deployment"
            fi
